### ISSUE TITLE
Issues when changing build configurations (runtime and test)

### ISSUE THREAD

**Issue by markjohndoyle** [sdedwards/m2e-nar#2]
On the latest versions of Eclipse (Oxygen or Neon) there is an issue with the build configurations generated by the plugin. 

When changing configuration, e.g., to the test config, the project explorer does not update and the indexer complains about missing symbols etc. I think the project explorer, editor, indexer, parser act like they are in the previous config. The source locations do not change in the explorer I can see they have changed in Project > Properties > C/C++ General > Paths and Symbols > Source Location

When running a build on the active configuration, eclipse does build the correct config.

I'm not 100% sure this is the m2e-nar or just a bug introduced by CDT or eclipse. If I had to guess i'd say CDT probably changed the way build configs work and m2e-nar is using an outdated method.

**Comment by sdedwards** [comment]
Check that you have selected "Use active build configuration" in the Cdt indexer preferences: 

https://help.eclipse.org/neon/index.jsp?topic=%2Forg.eclipse.cdt.doc.user%2Freference%2Fcdt_u_indexer_preference.html

I think this is a workspace level setting you have to configure with each new workspace

**Comment by markjohndoyle** [comment]
Worked, thanks!

You were correct, you can change it once in the main Project preferences.
