### ISSUE TITLE
m2e-nar upgrade to nar-maven-plugin 3.5.1

### ISSUE THREAD

**Issue by sylar501** [sdedwards/m2e-nar#4]
Hi sdedwards,

Are there any plans to upgrade the m2e-nar plugin to work with nar-maven-plugin 3.5.1 ?

As of today, using nar-maven-plugin 3.5.1 in pom.xml causes the following error:

Unable to parse configuration of mojo com.github.maven-nar:nar-maven-plugin:3.5.1:nar-compile for parameter embedManifest: Cannot find 'embedManifest' in class com.github.maven_nar.NarCompileMojo
Cannot find 'embedManifest' in class com.github.maven_nar.NarCompileMojo

I have tried reverting to nar-maven-plugin 3.2.3, but doing so makes me lose the recent (and precious) updates to the nar plugin, such as the os-linker combinations or msvc toolchain specification.

Many thanks.

**Comment by sdedwards** [comment]
Yes this is known issue. A fix is in the works, hopefully for this week.

**Comment by sylar501** [comment]
Music to my ears :)

Many thanks for your work !
